### ISSUE TITLE
Acronyms inside brackets are not parsed

### ISSUE THREAD

**Issue by tomncooper** [Enet4/pandoc-ac#1]
Firstly thanks for making this filter. 

I have spotted an issue when the acronym string is itself at the end of a bracket. For example "(+ESQ)" parses fine, but "(see details of (+ESQ))" will fail. I presume this is because the regex looking for the acronym would find "ESQ" in the first example and "ESQ)" in the second (which will not match a defined acronym)? 

It may just be a tweak to get it to stop at the first ")"? I would try submitting a PR but I am not up to speed on Rust (yet).

**Comment by Enet4** [comment]
Thank you for reporting! Can you have a second try with the upstream version from the master branch? I recall having addressed that problem in some way, but it's probably not released yet.

With Cargo: `cargo install --git https://github.com/Enet4/pandoc-ac --force`

**Comment by tomncooper** [comment]
Yep, the master branch version parses everything fine! Fastest bug fix ever ;-)

**Comment by Enet4** [comment]
Thank you for reminding me of this, nevertheless! I have just released v0.2.0 with all of my latest tweaks to the filter.
