### ISSUE TITLE
Upgrade pandoc_ast

### ISSUE THREAD

**Issue by matclab** [Enet4/pandoc-ac#3]
Pandoc_ast is now at 0.8.0.

For now I get the error : 
```
pandoc -f markdown --filter pandoc-crossref --filter pandoc-ac --pdf-engine=xelatex -o notes.pdf notes.md
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `[1, 22]`,
 right: `[1, 20]`: please file a bug report against `pandoc-ast` to update for the newest pandoc version', /home/clabaut/.cargo/git/checkouts/pandoc-ast-74047830f14f09b7/b2b2a88/src/lib.rs:33:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error running filter pandoc-ac:
Filter returned error status 101

```

**Comment by Enet4** [comment]
Thank you for reporting. Could you please check whether #4 works for you?

**Comment by matclab** [comment]
Yes, I've no error when running the command with the new pandoc-ac from this PR (I have still to understand how to define acronyms as:
```
acronyms:
  ATC: acronyme test case
```

doesn't seem to work).

**Comment by Enet4** [comment]
I'm afraid that I am unfamiliar with that way of declaring acronyms. Back then, I made them in LaTeX directly, so that the family of `\ac` macros would just work.

It might help to inspect the intermediate tex output and see whether or how the current pipeline is declaring acronyms.
